name: Build PR
on: 
  workflow_dispatch:
    inputs:
      pr:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v7
      - run: git remote add upstream https://github.com/yt-dlp/yt-dlp.git
      - run: git fetch
      - run: git checkout -b yt-dlp-master upstream/master
      - run: gh pr checkout ${{ github.event.inputs.pr }} -R yt-dlp/yt-dlp
      - run: git rebase yt-dlp-master
      - run: git push --force origin HEAD:PR${{ github.event.inputs.pr }}
      - run: gh workflow run release.yml --ref PR${{ github.event.inputs.pr }} -f source=yt-dlp/yt-dlp -f target=$GITHUB_REPOSITORY@PR${{ github.event.inputs.pr }} -f prerelease=true
      
